# This is an ESP-IDF workflow to build an ESP32-S3 based project

name: Build and Artifact the ESP-IDF Project

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESP-IDF and build project
        uses: rmshub/esp-idf-action@v6
        with:
          esp_idf_version: v6.0
          esp_idf_target: esp32s3

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
